name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: python3 ../fmSynth/configure.py
      shell: bash
    - name: make
      run: python3 ../fmSynth/run.py
      shell: bash
