name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt-get install build-essential xorg-dev alsa libwebkit2gtk-4.0-dev libgtk-3-dev libcurl4-openssl-dev libasound2-dev
      shell: bash
      
    - name: Cache FRUT/JUCE
      uses: actions/cache@v1.1.2
      with:
        # A directory to store and save the cache
        path: $GITHUB_WORKSPACE/external 
        # An explicit key for restoring and saving the cache
        key: juce-frut-03-08-2019
      
    
    - name: configure
      run: python3 configure.py
      working-directory: ./fmSynth
      shell: bash
    - name: make
      run: python3 run.py
      working-directory: ./fmSynth
      shell: bash
      
    - name: configure UnitTests
      run: python3 configure.py
      working-directory: ./UnitTests
      shell: bash
    - name: run UnitTests
      run: python3 run.py
      working-directory: ./UnitTests
      shell: bash
